version: '3'

services:
  db_api_test:
    image: postgres
    container_name: db_api_test_2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - '5440:5432'
    volumes:
      - db_api_test:/var/lib/postgresql/data
    networks:
      - net_api_test

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - '1025'
      - '8025'
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - net_api_test
###< symfony/mailer ###

volumes:
  db_api_test:

networks:
  net_api_test:
    driver: bridge
